import { MyButton } from "widgets.slint";
import { FrameworkState, FrameworkBackend, OtaState, WebConfigState, ResetWifiCredentialsState, ResetFixedSecurityKeyState, RestartDeviceState } from "framework.slint";
import { Title, LeftTab } from "widgets.slint";
import { AppBackend } from "../app.slint";
import { Translations } from "../translations.slint";
import { StandardListView } from "std-widgets.slint";

export component MyText inherits Text {
    height: 22px;
    font-size: 20px;
}

export component SettingsButton inherits MyButton {
    height: 56px;
}

export component WebConfigButton inherits SettingsButton {
    // enabled: FrameworkState.web-config-state == WebConfigState.Stopped || FrameworkState.web-config-state == WebConfigState.Started-STA;
    text: (FrameworkState.web-config-state == WebConfigState.Started-STA ? Translations.tr-web-config-instructions : Translations.tr-close);
    clicked => {
        if FrameworkState.web-config-state == WebConfigState.Started-STA {
            FrameworkState.web-config-state = WebConfigState.Started-STA-Displayed;
        } else if FrameworkState.web-config-state == WebConfigState.Started-STA-Displayed {
            FrameworkState.web-config-state = WebConfigState.Started-STA;
        }
        // if FrameworkState.web-config-state == WebConfigState.Stopped {
        //     // Order is important
        //     FrameworkState.web-config-state = WebConfigState.Starting;
        //     FrameworkBackend.start-web-config();
        //     AppBackend.emulate-tag-web-config();
        // } else {
        //     // Order is important
        //     FrameworkState.web-config-state = WebConfigState.Stopping;
        //     FrameworkBackend.stop-web-config();
        //     AppBackend.read-tag-mode();
        // }
    }
}

export component RestartDeviceButton inherits SettingsButton {
    text: Translations.tr-restart-device;
    clicked => {
        FrameworkState.restart-device-state = RestartDeviceState.UserInput;
    }
}

export component ResetWifiCredentialsButton inherits SettingsButton {
    text: Translations.tr-reset-wifi;
    clicked => {
        FrameworkState.reset-wifi-credentials-state = ResetWifiCredentialsState.UserInput;
    }
}

export component ResetFixedKeyButton inherits SettingsButton {
    text: Translations.tr-reset-fixed-key;
    clicked => {
        FrameworkState.reset-fixed-security-key-state = ResetFixedSecurityKeyState.UserInput;
    }
}

export component OtaButton inherits SettingsButton {
    text: Translations.tr-check-update-firmware;// + (FrameworkState.ota-info.newer ? " to \{FrameworkState.ota-info.version}" : "");
    clicked => {
        FrameworkState.ota-state = OtaState.Checking;
        FrameworkState.ota-clear-message();
        AppBackend.ota-check-firmwares();
    }
}

export component SettingsConfirm inherits VerticalLayout {
    in-out property <string> title;
    in-out property <string> text;
    in-out property <string> positive-text: Translations.tr-confirm-yes-ok;
    in-out property <string> negative-text: Translations.tr-confirm-no-cancel;
    callback clicked-positive;
    callback clicked-negative;
    alignment: space-between;
    VerticalLayout {
        alignment: stretch;
        spacing: 10px;

        Title {
            vertical-stretch: 0;
            text: title;
        }

        VerticalLayout {
            vertical-stretch: 1;
            alignment: center;
            padding-left: 5px;
            padding-right: 5px;
            Rectangle {
                Text {
                    width: parent.width;
                    vertical-stretch: 1;
                    vertical-alignment: center;
                    horizontal-alignment: left;
            // height: 100px;
            text: text;
                    color: black;
                    font-size: 20px;
                    wrap: word-wrap;
                }
            }
        }
    }

    HorizontalLayout {
        SettingsButton {
            text: positive-text;
            clicked => {
                root.clicked-positive()
            }
        }

        SettingsButton {
            text: negative-text;
            clicked => {
                root.clicked-negative()
            }
        }
    }
}

////////////////////////////////////

export component FrameworkSettingsButtons inherits VerticalLayout {
    callback ota-clicked;
    VerticalLayout {
        WebConfigButton { }

        ResetWifiCredentialsButton { }

        ResetFixedKeyButton { }

        RestartDeviceButton { }

        OtaButton { }
    }
}


// Reset Wifi Credentials
export component FrameworkSettingsDetails inherits Rectangle {
    background: white;
    if FrameworkState.reset-wifi-credentials-state == ResetWifiCredentialsState.UserInput: 
        SettingsConfirm {
        title: Translations.tr-settings-reset-wifi-title;
        text: Translations.tr-settings-reset-wifi-text;
        clicked-positive => {
            FrameworkBackend.reset-flash-wifi-credentials();
        }
        clicked-negative => {
            FrameworkState.reset-wifi-credentials-state = ResetWifiCredentialsState.NotStarted;
        }
    }

// Reset Fixed Security Key
    if FrameworkState.reset-fixed-security-key-state == ResetFixedSecurityKeyState.UserInput: 
        SettingsConfirm {
        title: Translations.tr-settings-reset-key-title;
        text: Translations.tr-settings-reset-key-text;
        clicked-positive => {
            FrameworkBackend.reset-fixed-security-key();
            FrameworkState.reset-fixed-security-key-state = ResetFixedSecurityKeyState.NotStarted;
        }
        clicked-negative => {
            FrameworkState.reset-fixed-security-key-state = ResetFixedSecurityKeyState.NotStarted;
        }
    }

// Restart Device
    if FrameworkState.restart-device-state == RestartDeviceState.UserInput: 
        SettingsConfirm {
        title: Translations.tr-restart-device;
        text: Translations.tr-settings-restart-text-pre + FrameworkState.app-info.name + Translations.tr-settings-restart-text-post;
        clicked-positive => {
            FrameworkBackend.reset-device();
        }
        clicked-negative => {
            FrameworkState.restart-device-state = RestartDeviceState.NotStarted;
        }
    }
// Basic OTA, more complex is for this specific app
    // if FrameworkState.ota-state == OtaState.UserInput: 
    //     SettingsConfirm {
    //     title: "Over the Air Network Update";
    //     text: "Check for firmware updates and install if available?\n\nIMPORTANT: This is an Alpha version—make sure you know what you’re updating to.\n\nThe process may take a few minutes.";
    //     clicked-positive => {
    //         FrameworkBackend.update-firmware-ota();
    //     }
    //     clicked-negative => {
    //         FrameworkState.ota-state = OtaState.NotStarted;
    //     }
    // }

    if FrameworkState.ota-state != OtaState.NotStarted && FrameworkState.ota-state != OtaState.UserInput: ota-run := VerticalLayout {
        alignment: stretch;
        Rectangle {
            vertical-stretch: 1;
            width: parent.width;
            background: FrameworkState.ota-state == OtaState.Failed ? red : FrameworkState.ota-state == OtaState.Completed ? lightgreen : white;
            border-color: black;
            border-width: 1px;
            Text {
                horizontal-alignment: center;
                color: black;
                text: FrameworkState.ota-message;
                font-size: 20px;
            }
        }

        SettingsButton {
            enabled: FrameworkState.ota-state == OtaState.Failed || FrameworkState.ota-state == OtaState.Completed || FrameworkState.ota-allow-close-during-update;
            text: Translations.tr-ok + (FrameworkState.ota-allow-close-during-update ? " (" + Translations.tr-settings-ota-ok-continue + ")" : "");
            clicked => {
                FrameworkState.ota-state = OtaState.NotStarted;
            }
        }
    }

// Web Config

    if (FrameworkState.web-config-state == WebConfigState.Started-STA-Displayed || FrameworkState.web-config-state == WebConfigState.Started-AP): web-config := VerticalLayout {
        alignment: stretch;
        Rectangle {
            height: 320px - 56px; // TODO: why need to specify height? should be automatic by layout
            background: white;
            vertical-stretch: 1;
            width: parent.width;
            border-color: black;
            border-width: 1px;
            VerticalLayout {
                padding: 10px;
                spacing: 10px;
                preferred-height: 500px;
                MyText {
                    text: Translations.tr-wc-step1;
                }

                MyText {
                    text: Translations.tr-wc-wifi-network + FrameworkState.web-config-ssid;
                }

                MyText {
                    text: FrameworkState.web-config-state == WebConfigState.Started-AP ? Translations.tr-wc-step2-ap : Translations.tr-wc-step2-sta;
                }

                MyText {
                    text: "    \{FrameworkState.web-config-url}";
                }

                MyText {
                    text: Translations.tr-wc-step3;
                }

                MyText {
                    text: Translations.tr-wc-security-key + FrameworkState.web-config-key;
                }

                MyText {
                    text: Translations.tr-wc-step4a;
                }

                MyText {
                    text: Translations.tr-wc-step4b;
                }
            }
        }

        if FrameworkState.web-config-state != WebConfigState.Started-AP: WebConfigButton { } // when STA - Will show disable button
        if FrameworkState.web-config-state == WebConfigState.Started-AP: RestartDeviceButton { } // when AP - Will show restart device button
    }
}

export component Settings inherits Rectangle {
    callback ota-clicked();
    in-out property <string> selected-tab: tabs.selected-index;
    in-out property <length> x-offset: tabs.width;
    in-out property <length> y-offset: title.height;
    in-out property <length> buttons-width: self.width - x-offset;
    in-out property <[string]> tabs;

    property <bool> framework-buttons-visible:  FrameworkState.restart-device-state == RestartDeviceState.NotStarted && FrameworkState.reset-fixed-security-key-state == ResetFixedSecurityKeyState.NotStarted && FrameworkState.ota-state == OtaState.NotStarted && FrameworkState.web-config-state != WebConfigState.Started-STA-Displayed && FrameworkState.web-config-state != WebConfigState.Started-AP && FrameworkState.reset-wifi-credentials-state == ResetWifiCredentialsState.NotStarted;
    in property <bool> framework-tab-selected;
    VerticalLayout {
        title := Title {
            text: "  Installed firmware: \{FrameworkState.app-info.name} \{ FrameworkState.app-info.version}";
        }

        tabs := LeftTab {
            tabs: root.tabs;
        }
    }

    // Settings includes by default the framework settings, everything else is added where used

    if framework-tab-selected && framework-buttons-visible: 
      FrameworkSettingsButtons {
        x: x-offset;
        y: y-offset;
        width: buttons-width;
    }

    FrameworkSettingsDetails {
        visible: framework-tab-selected && !framework-buttons-visible;
        width: parent.width;
        height: parent.height;
    }
}
