import { MyText, MyButton, Title } from "framework/widgets.slint";
import { SettingsButton } from "framework/settings.slint";
import { ScaleCalibration } from "scale-calibration.slint";
import { AppBackend, AppState, SpoolScaleState } from "app.slint";
import { Settings } from "framework/settings.slint";
import { Translations } from "translations.slint";

enum AppSettingsState {
  Buttons,
  ScaleCalibration,
  ScalesInformation,
  LanguageSettings,
}

export component ScalesInformation inherits Rectangle {
    callback clicked;

    background: white;
    VerticalLayout {
        alignment: space-between;
        VerticalLayout {
            alignment: start;
            title := Title {
                width: root.width;
                text: AppState.spool-scale-state == SpoolScaleState.NotAvailable ? Translations.tr-scale-not-available :
                     (AppState.spool-scale-state == SpoolScaleState.Unknown || AppState.spool-scale-state == SpoolScaleState.Disconnected) ? Translations.tr-trying-to-connect-scale :
                     Translations.tr-connected-to-scale;
            }

            MyText {
                vertical-alignment: center;
                width: root.width;
                height: title.height;
                text: AppBackend.get-connected-scale-info();
            }

            Title {
                width: root.width;
                text: Translations.tr-scales-on-network;
            }

            for scale in AppBackend.get-available-scales-info(): MyText {
                vertical-alignment: center;
                width: root.width;
                height: 30px;
                text: scale;
            }
        }

        MyButton {
            clicked => {
                root.clicked()
            }
            width: root.width;
            height: 56px;
            text: Translations.tr-ok;
        }
    }
}

component LanguageSettings inherits Rectangle {
    callback clicked;
    background: white;
    VerticalLayout {
        alignment: space-between;
        VerticalLayout {
            alignment: start;
            Title {
                width: root.width;
                text: Translations.tr-language-settings;
            }
            MyButton {
                width: root.width;
                height: 56px;
                text: "English";
                clicked => {
                    AppBackend.set-language("en");
                }
            }
            MyButton {
                width: root.width;
                height: 56px;
                text: "Polski";
                clicked => {
                    AppBackend.set-language("pl");
                }
            }
        }
        MyButton {
            clicked => {
                root.clicked()
            }
            width: root.width;
            height: 56px;
            text: Translations.tr-ok;
        }
    }
}

export component AppSettings inherits Settings {
    callback done;
    property <AppSettingsState> state: Buttons;
    tabs: ["1", "2"];

    framework-tab-selected: self.selected-tab == 0;

    if self.selected-tab == 1 && state == AppSettingsState.Buttons: VerticalLayout {
        x: parent.x-offset;
        y: parent.y-offset;
        width: parent.buttons-width;

        SettingsButton {
            text: Translations.tr-calibrate-scale;
            enabled: !(AppState.spool-scale-state == SpoolScaleState.NotAvailable || AppState.spool-scale-state == SpoolScaleState.Unknown || AppState.spool-scale-state == SpoolScaleState.Disconnected);
            clicked => {
                root.state = AppSettingsState.ScaleCalibration;
            }
        }

        SettingsButton {
            text: Translations.tr-scale-information;
            clicked => {
                root.state = AppSettingsState.ScalesInformation;
            }
        }

        SettingsButton {
            text: Translations.tr-language-settings;
            clicked => {
                root.state = AppSettingsState.LanguageSettings;
            }
        }
    }

    if state == AppSettingsState.ScaleCalibration: ScaleCalibration {
        cancel-clicked => {
            root.state = AppSettingsState.Buttons;
        }
        ok-clicked => {
            root.state = AppSettingsState.Buttons;
            root.done();
        }
    }

    if state == AppSettingsState.ScalesInformation: ScalesInformation {
        clicked => {
            root.state = AppSettingsState.Buttons;
        }
    }

    if state == AppSettingsState.LanguageSettings: LanguageSettings {
        clicked => {
            root.state = AppSettingsState.Buttons;
        }
    }
}
