import { Title, MyText, MyButton, WizardButtons } from "framework/widgets.slint";
import { ScaleWeightDisplay } from "app-widgets.slint";
import { AppBackend, AppState } from "app.slint";
import { Translations } from "translations.slint";

enum UpdateWeightSelect {
  None,
  UsedKeepNew,
  Unused,
  UsedClearNew
}

export component UpdateWeightPage inherits Rectangle {
    callback after-next-clicked;
    callback cancel-clicked;
    callback back-clicked;
    height: 320px;
    width: 480px;
    in-out property <bool> unused: unused.pushed;
    in property <int> weight-current: 0;
    in property <int> weight-new: 0;
    in property <string> spool-id;
    in property <string> title;
    in property <string> user-prompt;
    in property <bool> final-step: false;
    property <UpdateWeightSelect> update-weight-select: weight-current != 0 ? UsedKeepNew : None;
    background: white;
    function pressed(operation: UpdateWeightSelect) {
        update-weight-select = operation;
    }
    VerticalLayout {
        Title {
            text: title;
        }

        VerticalLayout {
            alignment: start;
            padding: 5px;
            spacing: 8px;

            Rectangle {
                VerticalLayout {
                    spacing: 8px;
                    Rectangle {
                        MyText {
                            width: parent.width;
                            text: user-prompt;
                            wrap: word-wrap;
                        }
                    }

                    HorizontalLayout {
                        alignment: center;
                        scale-display := ScaleWeightDisplay {
                            weight-display-content: Gross;
                            width: 160px;
                        }
                    }

                    MyText {
                        width: parent.width;
                        text: Translations.tr-then-select-weight-update;
                    }

                    HorizontalLayout {
                        x: - 5px;
                        width: parent.width + 10px;
                        height: 86px;
                        used := MyButton {
                            type: RadioButton;
                            text: weight-new != 0 ? Translations.tr-used-keep-full-weight : Translations.tr-used-simple;
                            pushed: update-weight-select == UpdateWeightSelect.UsedKeepNew;
                            clicked => {
                                root.pressed(UpdateWeightSelect.UsedKeepNew);
                            }
                        }

                        unused := MyButton {
                            type: RadioButton;
                            text: Translations.tr-full-unused;
                            pushed: update-weight-select == UpdateWeightSelect.Unused;
                            clicked => {
                                root.pressed(UpdateWeightSelect.Unused);
                            }
                        }

                        if weight-new != 0: clear-new-weight := MyButton {
                            type: RadioButton;
                            text: Translations.tr-used-clear-new;
                            pushed: update-weight-select == UpdateWeightSelect.UsedClearNew;
                            clicked => {
                                root.pressed(UpdateWeightSelect.UsedClearNew);
                            }
                        }
                    }
                }
            }
        }

        WizardButtons {
            back-enabled: true;
            next-enabled: scale-display.stable-weight && update-weight-select != UpdateWeightSelect.None;
            cancel-enabled: true;
            next-text: Translations.tr-update-weight;
            cancel-clicked => {
                root.cancel-clicked();
            }
            next-clicked => {
                if root.update-weight-select == UpdateWeightSelect.UsedKeepNew {
                    AppBackend.set-spool-weight(root.spool-id, AppState.spool-scale-weight, -1, final-step);
                } else if root.update-weight-select == UpdateWeightSelect.Unused {
                    AppBackend.set-spool-weight(root.spool-id, AppState.spool-scale-weight, AppState.spool-scale-weight, final-step);
                } else if root.update-weight-select == UpdateWeightSelect.UsedClearNew {
                    AppBackend.set-spool-weight(root.spool-id, AppState.spool-scale-weight, 0, final-step);
                }
                root.after-next-clicked();
            }
            back-clicked => {
                root.back-clicked();
            }
        }
    }
}
