import { MyText, MyButton, ButtonType, WizardButtons, Title } from "framework/widgets.slint";
import { NumPad } from "numpad.slint";
import { AppBackend, AppState, ControlState, NewTagScanPage, NewTagOperation, SpoolScaleState, UiSpoolRecordDisplay } from "app.slint";
import { Utils } from "utils.slint";
import { ScaleWeightDisplay } from "app-widgets.slint";
import { SpoolDisplay } from "spool-display.slint";
import { UpdateWeightPage } from "common-operations.slint";

component OperationSelectionStep inherits Rectangle {
    background: white;
    function pressed(operation: NewTagOperation) {
        AppState.new-tag-operation = AppState.new-tag-operation == operation ? NewTagOperation.None : operation;
    }

    VerticalLayout {
        Title {
            text: "New Tag Scanned";
        }

        VerticalLayout {
            alignment: start;
            padding: 5px;
            padding-top: 10px;
            spacing: 8px;
            Rectangle {
                MyText {
                    width: parent.width;
                    wrap: word-wrap;
                    text: "New Tag Scanned — Please Choose an Action";
                    color: black;
                }
            }

            VerticalLayout {
                b1 := MyButton {
                    type: ButtonType.RadioButton;
                    pushed: AppState.new-tag-operation == NewTagOperation.LinkTagToSpoolId;
                    height: 56px;
                    text: "Link Tag to an Untagged Spool";
                    pressed => {
                        pressed(NewTagOperation.LinkTagToSpoolId);
                    }
                }

                b2 := MyButton {
                    visible: AppBackend.recently_added_spool_id_if_untagged() != "";
                    pushed: AppState.new-tag-operation == NewTagOperation.LinkTagToRecentlyAddedSpool;
                    type: ButtonType.RadioButton;
                    height: 56px;
                    text: "Link Tag to Recently Added Spool (ID: \{AppBackend.recently_added_spool_id_if_untagged()})";
                    pressed => {
                        pressed(NewTagOperation.LinkTagToRecentlyAddedSpool);
                    }
                }
            }
        }

        WizardButtons {
            next-enabled: AppState.new-tag-operation != NewTagOperation.None;
            next-clicked => {
                // AppState.new-tag-operation = selected-operation;
              if AppState.new-tag-operation == NewTagOperation.LinkTagToSpoolId {
                    AppState.new-tag-scan-page = NewTagScanPage.SpoolSelect;
                } else {
                    AppState.new-tag-scan-spool-id = AppBackend.recently_added_spool_id_if_untagged();
                    AppState.new-tag-scan-page = NewTagScanPage.LinkSpoolDisplay;
                }
            }
            cancel-clicked => {
                AppState.control-state = ControlState.Ready;
            }
        }
    }
}

component SpoolSelectStep inherits Rectangle {
    background: white;
    in-out property <int> spool-id: num-pad.number;
    VerticalLayout {
        Title {
            text: "Please Select Spool Id to Link";
        }

        Rectangle {
            num-pad := NumPad {
                number: AppState.new-tag-scan-spool-id-int;
                ok-visible: false;
                display-postfix: "";
            }
        }

        wiz-buttons := WizardButtons {
            back-enabled: true;
            next-enabled: true;
            back-clicked => {
                AppState.new-tag-scan-page = NewTagScanPage.OperationSelect;
            }
            cancel-clicked => {
                AppState.control-state = ControlState.Ready;
            }
            next-clicked => {
                num-pad.display-error = AppBackend.can-link-spool-to-tag(num-pad.number);
                if num-pad.display-error == "" {
                    AppState.new-tag-scan-spool-id = num-pad.number;
                    AppState.new-tag-scan-spool-id-int = num-pad.number;
                    AppState.new-tag-scan-page = NewTagScanPage.LinkSpoolDisplay;
                }
            }
        }
    }
}

component V1TagPromptStep inherits Rectangle {
    width: 480px;
    height: 320px;
    property <NewTagOperation> selected-operation: None;
    property <bool> last-step: !AppState.is-scale-usable-now();
    function pressed(operation: NewTagOperation) {
        selected-operation = selected-operation == operation ? NewTagOperation.None : operation;
    }
    background: white;
    VerticalLayout {
        Title {
            text: "Early Version Tag That's Not in Inventory";
        }

        VerticalLayout {
            alignment: start;
            padding: 5px;
            spacing: 5px;
            MyText {
                text: "This scanned tag is from an earlier SpoolEase version and isn’t in your inventory.";
                wrap: word-wrap;
            }

            MyText {
                text: "Please choose an action:";
            }

            b1 := MyButton {
                type: ButtonType.RadioButton;
                pushed: selected-operation == NewTagOperation.AddV1TagToInventory;
                height: 56px;
                text: "Add Spool Data to Inventory";
                pressed => {
                    pressed(NewTagOperation.AddV1TagToInventory);
                }
            }

            b2 := MyButton {
                pushed: selected-operation == NewTagOperation.EraseV1Tag;
                type: ButtonType.RadioButton;
                height: 56px;
                text: "Erase Tag to Use it Without the Data";
                pressed => {
                    pressed(NewTagOperation.EraseV1Tag);
                }
            }
        }

        WizardButtons {
            back-enabled: false;
            next-enabled: selected-operation != NewTagOperation.None;
            cancel-enabled: true;
            cancel-clicked => {
                AppState.control-state = ControlState.Ready;
            }
            next-clicked => {
                if selected-operation == NewTagOperation.AddV1TagToInventory {
                    AppBackend.add-v1-tag-to-inventory(AppState.new-tag-scan-tag-id, AppState.new-tag-scan-v1-tag, last-step);
                    // AppState.control-state = ControlState.Ready;
                } else {
                    AppBackend.erase-tag(AppState.new-tag-scan-tag-id);
                    AppState.control-state = ControlState.Ready;
                }
            }
        }
    }
}

component SpoolDisplayStep inherits Rectangle {
    in-out property <string> cancel-text: "";
    in-out property <string> next-text: "";
    in property <UiSpoolRecordDisplay> spool-display;
    property <bool> last-step: !AppState.is-scale-usable-now();
    VerticalLayout {
        SpoolDisplay {
            show-title: true;
            spool-display: root.spool-display;
        }

        WizardButtons {
            back-enabled: true;
            next-enabled: true;
            cancel-enabled: true;
            cancel-text: root.cancel-text;
            next-text: "✓ Link Tag" + (root.last-step ? "" : " ▶");
            back-clicked => {
                AppState.new-tag-scan-page = NewTagScanPage.SpoolSelect;
            }
            next-clicked => {
                self.back-enabled = false;
                self.next-enabled = false;
                cancel-text = "Close";
                // perform action
                AppBackend.link_tag_to_spool_id(AppState.new-tag-scan-tag-id, AppState.new-tag-scan-spool-id, last-step);
            }
            cancel-clicked => {
                AppState.control-state = ControlState.Ready;
            }
        }
    }
}

component StatusDisplayPage inherits Rectangle {
    in-out property <bool> success: AppState.new-tag-scan-status == "";
    in-out property <string> message: self.success ? "Tag Linked to Spool Successfuly" : AppState.new-tag-scan-status;
    VerticalLayout {
        Rectangle {
            background: success ? lightgreen : red;
            MyText {
                text: message;
                color: Utils.contrasting_color(parent.background);
            }
        }

        WizardButtons {
            back-enabled: false;
            next-enabled: false;
            cancel-enabled: true;
            cancel-text: "Close";
            cancel-clicked => {
                AppState.control-state = ControlState.Ready;
            }
        }
    }
}

export component NewTagScan inherits Rectangle {
    width: 480px;
    height: 320px;
    property <UiSpoolRecordDisplay> spool-display: AppBackend.get-spool-record-display(AppState.new-tag-scan-spool-id);

    if AppState.new-tag-scan-page == NewTagScanPage.OperationSelect: oper-select := OperationSelectionStep { }

    if AppState.new-tag-scan-page == NewTagScanPage.SpoolSelect: spool-select := SpoolSelectStep { }

    if AppState.new-tag-scan-page == NewTagScanPage.LinkSpoolDisplay: spool-display := SpoolDisplayStep {
        spool-display: root.spool-display;
    }

    if AppState.new-tag-scan-page == NewTagScanPage.UpdateWeight: update-weight-display := UpdateWeightPage {
        final-step: true;
        title: "Linking Tag Succeeded, Measure Weight";
        user-prompt: "Now is a good time to measure spool weight,\nplease place it on the scale.";
        weight-current: spool-display.spool-record.weight-current;
        weight-new: spool-display.spool-record.weight-new;
        spool-id: spool-display.spool-record.id;
        cancel-clicked => {
            AppState.control-state = ControlState.PostAction; // so will show the message that tag was scanned from previous step
        }
        back-clicked => {
            AppState.staging-operation-page = AppState.prev-staging-operation-page;
        }
    }

    if AppState.new-tag-scan-page == NewTagScanPage.StatusDisplay: status-display := StatusDisplayPage { }

    if AppState.new-tag-scan-page == NewTagScanPage.V1TagPrompt: v1-prompt := V1TagPromptStep { }
}
