import { MyText, MyButton, ButtonType, WizardButtons, Title } from "framework/widgets.slint";
import { NumPad } from "numpad.slint";
import { AppBackend, AppState, ControlState, NewTagScanPage, NewTagOperation, SpoolScaleState, UiSpoolRecordDisplay, NewScannedTagType } from "app.slint";
import { Utils } from "utils.slint";
import { ScaleWeightDisplay } from "app-widgets.slint";
import { SpoolDisplay, SpoolDisplayMode } from "spool-display.slint";
import { UpdateWeightPage } from "common-operations.slint";
import { Translations } from "translations.slint";

enum AddSelection {
  None,
  Yes,
  No
}

component SpoolDefinitionTagScannedPage inherits Rectangle {
    background: white;
    property <AddSelection> add-selection: None;

    function pressed(operation: AddSelection) {
        add-selection = (operation == AddSelection.Yes) ? AddSelection.Yes : AddSelection.No;
    }

    VerticalLayout {
        Title {
            text: Translations.tr-new-def-tag-scanned-prefix + AppState.new-tag-scan-definition-type + Translations.tr-new-def-tag-scanned-suffix;
        }

        VerticalLayout {
            alignment: start;
            padding: 5px;
            padding-top: 10px;
            spacing: 8px;

            MyText {
                wrap: word-wrap;
                text: Translations.tr-scanned-tag-not-linked-prefix + AppState.new-tag-scan-definition-type + Translations.tr-scanned-tag-not-linked-suffix;
                color: black;
            }

            MyText {
                text: Translations.tr-import-tag-to-inventory;
            }

            add-rec-yes := MyButton {
                type: ButtonType.RadioButton;
                pushed: add-selection == AddSelection.Yes;
                height: 56px;
                text: Translations.tr-yes-import;
                pressed => {
                    pressed(AddSelection.Yes);
                }
            }

            add-red-no := MyButton {
                type: ButtonType.RadioButton;
                pushed: add-selection == AddSelection.No;
                height: 56px;
                text: Translations.tr-no-ignore;
                pressed => {
                    pressed(AddSelection.No);
                }
            }
        }

        WizardButtons {
            next-enabled: add-selection != AddSelection.None;
            next-clicked => {
                if add-selection == AddSelection.Yes {
                   // Switch to SpoolDisplay to show the scanned spool information
                   if AppState.new-tag-scan-definition-type == "Bambu Lab" {
                        AppState.new-tag-scan-page = NewTagScanPage.BambulabSpoolTypeSelection;
                    } else {
                        AppState.new-tag-scan-page = NewTagScanPage.SpoolDisplay;
                    }
                } else if add-selection == AddSelection.No {
                    AppState.new-tag-scan-tag-type = NewScannedTagType.SimpleTag;
                    // DON'T set the AppState.new-tag-scan-tag-definition-type, this is used for filling in the type of tag even if data in't imported
                    AppState.new-tag-scan-page = NewTagScanPage.OperationSelect;
                }
            }

            cancel-clicked => {
                AppState.control-state = ControlState.Ready;
            }
        }
    }
}

enum BambulabSpoolTypeSelection {
  None,
  LowTemp,
  HighTemp,
  Other,
}
component BambulabSpoolTypePage inherits Rectangle {
    width: 480px;
    height: 320px;
    background: white;
    property <BambulabSpoolTypeSelection> spool-selection: None;

    function pressed(operation: BambulabSpoolTypeSelection) {
        spool-selection = operation;
    }

    VerticalLayout {
        Title {
            text: Translations.tr-new-def-tag-scanned-prefix + AppState.new-tag-scan-definition-type + Translations.tr-new-def-tag-scanned-suffix;
        }

        VerticalLayout {
            alignment: start;
            padding: 5px;
            padding-top: 10px;
            spacing: 8px;

            MyText {
                width: parent.width;
                wrap: word-wrap;
                text: Translations.tr-filament-est-needs-weight;
                color: black;
            }

            MyText {
                text: Translations.tr-what-spool-type;
            }

            lowtemp := MyButton {
                type: ButtonType.RadioButton;
                pushed: spool-selection == BambulabSpoolTypeSelection.LowTemp;
                height: 45px;
                text: Translations.tr-low-temp; // 208-212 + 38 (if change, change also below)
                pressed => {
                    pressed(BambulabSpoolTypeSelection.LowTemp);
                }
            }

            hightemp := MyButton {
                type: ButtonType.RadioButton;
                pushed: spool-selection == BambulabSpoolTypeSelection.HighTemp;
                height: 45px;
                text: Translations.tr-high-temp; // 223 + 38, (if change, change also below)
                pressed => {
                    pressed(BambulabSpoolTypeSelection.HighTemp);
                }
            }

            other := MyButton {
                type: ButtonType.RadioButton;
                pushed: spool-selection == BambulabSpoolTypeSelection.Other;
                height: 45px;
                text: Translations.tr-other-manual;
                pressed => {
                    pressed(BambulabSpoolTypeSelection.Other);
                }
            }
        }

        WizardButtons {
            next-enabled: spool-selection != BambulabSpoolTypeSelection.None;
            next-clicked => {
                AppState.new-tag-scan-empty-spool-weight = spool-selection == BambulabSpoolTypeSelection.LowTemp ? 250 : spool-selection == BambulabSpoolTypeSelection.HighTemp ? 260 : 0;
                AppState.new-tag-scan-page = NewTagScanPage.SpoolDisplay;
            }
            back-clicked => {
                AppState.new-tag-scan-page = NewTagScanPage.SpoolDefinitionTagScanned;
            }
            cancel-clicked => {
                AppState.control-state = ControlState.Ready;
            }
        }
    }
}

component OperationSelectionStep inherits Rectangle {
    background: white;
    function pressed(operation: NewTagOperation) {
        AppState.new-tag-operation = AppState.new-tag-operation == operation ? NewTagOperation.None : operation;
    }

    VerticalLayout {
        Title {
            text: AppState.new-tag-scan-tag-type == NewScannedTagType.SimpleTag ? Translations.tr-new-tag-scanned : Translations.tr-new-def-tag-scanned-prefix + AppState.new-tag-scan-definition-type + Translations.tr-new-def-tag-scanned-suffix;
        }

        VerticalLayout {
            alignment: start;
            padding: 5px;
            padding-top: 10px;
            spacing: 8px;
            if AppState.new-tag-scan-tag-type == NewScannedTagType.DefinitionTag: Rectangle {
                MyText {
                    width: parent.width;
                    wrap: word-wrap;
                    text: Translations.tr-def-tag-data-imported-prefix + AppState.new-tag-scan-definition-type + Translations.tr-def-tag-data-imported-middle + AppState.new-tag-scan-spool-id + Translations.tr-def-tag-data-imported-suffix;
                    color: black;
                }
            }
            Rectangle {
                MyText {
                    width: parent.width;
                    wrap: word-wrap;
                    text: (AppState.new-tag-scan-tag-type == NewScannedTagType.SimpleTag) ? Translations.tr-please-choose-action : Translations.tr-please-choose-how-to-proceed;
                    color: black;
                }
            }

            VerticalLayout {
                if AppState.new-tag-scan-tag-type == NewScannedTagType.SimpleTag: b1 := MyButton {
                    type: ButtonType.RadioButton;
                    pushed: AppState.new-tag-operation == NewTagOperation.LinkTagToSpoolId;
                    height: 56px;
                    text: Translations.tr-link-tag-to-untagged-spool;
                    pressed => {
                        pressed(NewTagOperation.LinkTagToSpoolId);
                    }
                }

                b2 := MyButton {
                    visible: AppBackend.recently_added_spool_id_if_untagged() != "";
                    pushed: AppState.new-tag-operation == NewTagOperation.LinkTagToRecentlyAddedSpool;
                    type: ButtonType.RadioButton;
                    height: 56px;
                    text: (AppState.new-tag-scan-tag-type == NewScannedTagType.SimpleTag) ? Translations.tr-link-tag-recent-prefix + AppBackend.recently_added_spool_id_if_untagged() : Translations.tr-link-tag-imported-prefix + AppBackend.recently_added_spool_id_if_untagged();
                    pressed => {
                        pressed(NewTagOperation.LinkTagToRecentlyAddedSpool);
                    }
                }
            }
        }

        WizardButtons {
            next-enabled: AppState.new-tag-operation != NewTagOperation.None;
            next-clicked => {
                // AppState.new-tag-operation = selected-operation;
              if AppState.new-tag-operation == NewTagOperation.LinkTagToSpoolId {
                    AppState.new-tag-scan-page = NewTagScanPage.SpoolSelect;
                } else {
                    AppState.new-tag-scan-spool-id = AppBackend.recently_added_spool_id_if_untagged();
                    if AppState.new-tag-scan-tag-type == NewScannedTagType.SimpleTag {
                        AppState.new-tag-scan-page = NewTagScanPage.SpoolDisplay;
                    } else { // DefinitionTag
                      // skip display since we saw it already
                        AppBackend.link_tag_to_spool_id(AppState.new-tag-scan-tag-id, AppState.new-tag-scan-definition-type, AppState.new-tag-scan-spool-id, !AppState.is-scale-usable-now());
                    }
                }
            }
            cancel-text: (AppState.new-tag-scan-tag-type == NewScannedTagType.SimpleTag) ? Translations.tr-btn-cancel-x : Translations.tr-done;
            cancel-clicked => {
                AppState.control-state = ControlState.Ready;
            }
        }
    }
}

component SpoolSelectStep inherits Rectangle {
    background: white;
    in-out property <int> spool-id: num-pad.number;
    VerticalLayout {
        Title {
            text: Translations.tr-please-select-spool-id;
        }

        Rectangle {
            num-pad := NumPad {
                number: AppState.new-tag-scan-spool-id-int;
                ok-visible: false;
                display-postfix: "";
            }
        }

        wiz-buttons := WizardButtons {
            back-enabled: true;
            next-enabled: true;
            back-clicked => {
                AppState.new-tag-scan-page = NewTagScanPage.OperationSelect;
            }
            cancel-clicked => {
                AppState.control-state = ControlState.Ready;
            }
            next-clicked => {
                num-pad.display-error = AppBackend.can-link-spool-to-tag(num-pad.number);
                if num-pad.display-error == "" {
                    AppState.new-tag-scan-spool-id = num-pad.number;
                    AppState.new-tag-scan-spool-id-int = num-pad.number;
                    AppState.new-tag-scan-page = NewTagScanPage.SpoolDisplay;
                }
            }
        }
    }
}

component V1TagPromptStep inherits Rectangle {
    width: 480px;
    height: 320px;
    property <NewTagOperation> selected-operation: None;
    property <bool> last-step: !AppState.is-scale-usable-now();
    function pressed(operation: NewTagOperation) {
        selected-operation = selected-operation == operation ? NewTagOperation.None : operation;
    }
    background: white;
    VerticalLayout {
        Title {
            text: "Early Version Tag That's Not in Inventory";
        }

        VerticalLayout {
            alignment: start;
            padding: 5px;
            spacing: 5px;
            MyText {
                text: "This scanned tag is from an earlier SpoolEase version and isn’t in your inventory.";
                wrap: word-wrap;
            }

            MyText {
                text: "Please choose an action:";
            }

            b1 := MyButton {
                type: ButtonType.RadioButton;
                pushed: selected-operation == NewTagOperation.AddV1TagToInventory;
                height: 56px;
                text: "Add Spool Data to Inventory";
                pressed => {
                    pressed(NewTagOperation.AddV1TagToInventory);
                }
            }

            b2 := MyButton {
                pushed: selected-operation == NewTagOperation.EraseV1Tag;
                type: ButtonType.RadioButton;
                height: 56px;
                text: Translations.tr-erase-tag-without-data;
                pressed => {
                    pressed(NewTagOperation.EraseV1Tag);
                }
            }
        }

        WizardButtons {
            back-enabled: false;
            next-enabled: selected-operation != NewTagOperation.None;
            cancel-enabled: true;
            cancel-clicked => {
                AppState.control-state = ControlState.Ready;
            }
            next-clicked => {
                if selected-operation == NewTagOperation.AddV1TagToInventory {
                    AppBackend.add-v1-tag-to-inventory(AppState.new-tag-scan-tag-id, AppState.new-tag-scan-definition-info, last-step);
                } else {
                    AppState.erase-tag-by-tag-id-start(AppState.new-tag-scan-tag-id);
                }
            }
        }
    }
}

component SpoolDisplayStep inherits Rectangle {
    in-out property <string> cancel-text: "";
    in-out property <string> next-text: "";
    in property <UiSpoolRecordDisplay> spool-display;
    property <bool> last-step: !AppState.is-scale-usable-now();
    VerticalLayout {
        SpoolDisplay {
            show-title: true;
            spool-display: root.spool-display;
            title: AppState.new-tag-scan-tag-type == NewScannedTagType.DefinitionTag ? "Spool Tag Information" : "";
            mode: AppState.new-tag-scan-tag-type == NewScannedTagType.DefinitionTag ? SpoolDisplayMode.ImportTagDefinition : SpoolDisplayMode.Normal;
        }

        WizardButtons {
            back-enabled: true;
            next-enabled: true;
            cancel-enabled: true;
            cancel-text: root.cancel-text;
            next-text: AppState.new-tag-scan-tag-type == NewScannedTagType.SimpleTag ? "✓ Link Tag" + (root.last-step ? "" : " ▶") : "✓ Import ▶";
            back-clicked => {
                if AppState.new-tag-scan-tag-type == NewScannedTagType.SimpleTag {
                    AppState.new-tag-scan-page = NewTagScanPage.SpoolSelect;
                } else if AppState.new-tag-scan-tag-type == NewScannedTagType.DefinitionTag {
                    if AppState.new-tag-scan-definition-type == "Bambu Lab" {
                        AppState.new-tag-scan-page = NewTagScanPage.BambulabSpoolTypeSelection;
                    } else {
                        AppState.new-tag-scan-page = NewTagScanPage.SpoolDefinitionTagScanned;
                    }
                }
            }
            next-clicked => {
                self.back-enabled = false;
                self.next-enabled = false;
                cancel-text = Translations.tr-close;
                // perform action
                if AppState.new-tag-scan-tag-type == NewScannedTagType.SimpleTag {
                    AppBackend.link_tag_to_spool_id(AppState.new-tag-scan-tag-id, AppState.new-tag-scan-definition-type, AppState.new-tag-scan-spool-id, last-step);
                } else {
                  // TODO: Add call to AppBackend to add spool record, which will 
                  // (1) import the tag to the inventory & set it as recently added spool
                  // (2) once completed will trigger move here to next step
                  AppBackend.import-definition-tag-to-inventory(AppState.new-tag-scan-definition-type, AppState.new-tag-scan-definition-info, AppState.new-tag-scan-empty-spool-weight);
                }
            }
            cancel-clicked => {
                AppState.control-state = ControlState.Ready;
            }
        }
    }
}

component ImportDefinitionNoticePage inherits Rectangle {
    width: 480px;
    height: 320px;
    VerticalLayout {

        Title {
            text: Translations.tr-def-tag-imported-prefix + AppState.new-tag-scan-definition-type + Translations.tr-def-tag-imported-suffix;
        }
        Rectangle {
          background: white;

          VerticalLayout {
              alignment: space-around;
              padding: 20px;
              spacing: 5px;
              MyText {
                  horizontal-alignment: center;
                  text: Translations.tr-tag-imported-to-spool-prefix + AppState.new-tag-scan-spool-id + Translations.tr-tag-imported-to-spool-suffix;
              }
              MyText {
                  text: Translations.tr-imported-data-may-be-incomplete;
                  wrap: word-wrap;
              }
              MyText {
                  text: Translations.tr-please-review-spool-record;
                  wrap: word-wrap;
              }
          }

        }


        WizardButtons {
            back-enabled: false;
            next-enabled: true;
            next-text: Translations.tr-continue;
            cancel-enabled: false;
            next-clicked => {
                AppState.new-tag-scan-page = NewTagScanPage.OperationSelect;
            }
            cancel-clicked => {
                AppState.control-state = ControlState.Ready;
            }
        }
    }
}

component StatusDisplayPage inherits Rectangle {
    in-out property <bool> success: AppState.new-tag-scan-status == "";
    in-out property <string> message: self.success ? Translations.tr-tag-linked-success : AppState.new-tag-scan-status;
    VerticalLayout {
        Rectangle {
            background: success ? lightgreen : red;
            MyText {
                text: message;
                color: Utils.contrasting_color(parent.background);
            }
        }

        WizardButtons {
            back-enabled: false;
            next-enabled: false;
            cancel-enabled: true;
            cancel-text: Translations.tr-close;
            cancel-clicked => {
                AppState.control-state = ControlState.Ready;
            }
        }
    }
}

export component NewTagScan inherits Rectangle {
    width: 480px;
    height: 320px;
    property <UiSpoolRecordDisplay> spool-display: AppState.new-tag-scan-tag-type == NewScannedTagType.SimpleTag || AppState.new-tag-scan-spool-id != "" ? AppBackend.get-spool-record-display(AppState.new-tag-scan-spool-id) : AppBackend.get-spool-tag-definition-display(AppState.new-tag-scan-definition-type, AppState.new-tag-scan-definition-info, AppState.new-tag-scan-empty-spool-weight);

    if AppState.new-tag-scan-page == NewTagScanPage.OperationSelect: oper-select := OperationSelectionStep { }

    if AppState.new-tag-scan-page == NewTagScanPage.SpoolSelect: spool-select := SpoolSelectStep { }

    if AppState.new-tag-scan-page == NewTagScanPage.SpoolDisplay: spool-display := SpoolDisplayStep {
        spool-display: root.spool-display;
    }

    if AppState.new-tag-scan-page == NewTagScanPage.UpdateWeight: update-weight-display := UpdateWeightPage {
        final-step: true;
        title: Translations.tr-linking-succeeded-measure-weight;
        user-prompt: Translations.tr-now-measure-weight;
        weight-current: spool-display.spool-record.weight-current;
        weight-new: spool-display.spool-record.weight-new;
        spool-id: spool-display.spool-record.id;
        cancel-clicked => {
            AppState.control-state = ControlState.PostAction; // so will show the message that tag was scanned from previous step
        }
        back-clicked => {
            AppState.staging-operation-page = AppState.prev-staging-operation-page;
        }
    }

    if AppState.new-tag-scan-page == NewTagScanPage.StatusDisplay: status-display := StatusDisplayPage { }

    if AppState.new-tag-scan-page == NewTagScanPage.V1TagPrompt: v1-prompt := V1TagPromptStep { }

    if AppState.new-tag-scan-page == NewTagScanPage.SpoolDefinitionTagScanned: spool-definition-tag-scanned := SpoolDefinitionTagScannedPage { }

    if AppState.new-tag-scan-page == NewTagScanPage.BambulabSpoolTypeSelection: bambulab-spool-type-selection := BambulabSpoolTypePage { }

    if AppState.new-tag-scan-page == NewTagScanPage.ImportDefinitionNotice: import-definition-notice := ImportDefinitionNoticePage { }
}
