import { MyButton, MyText } from "framework/widgets.slint";


export component Display inherits Rectangle {
    in-out property <int> number;
    padding-right: 40px;
    border-color: black;
    border-width: 1px;
    in-out property <string> postfix: " g";
    in-out property <string> display-error: "";

    HorizontalLayout {
        padding-right: 20px;
        padding-left: 10px;
        Rectangle {
            MyText {
                text: display-error;
                color: red;
            }
        }

        VerticalLayout {
            horizontal-stretch: 1;
            padding: 4px;
            alignment: center;
            Text {
                // preferred-height: 1px;
                min-height: 0px;
                text: "\{number}\{postfix}";
                font-size: 32px;
                horizontal-alignment: right;
                color: black;
            }
        }
    }
}

export component NumButton inherits MyButton {
    in property <int> digit;
    text: "\{digit}";
    callback key-pressed(digit: int);
    preferred-width: 1px; // so all equal
    preferred-height: 1px;
    clicked => {
        key-pressed(digit);
    }
}

////////////////////////

export component NumPad inherits Rectangle {
    in property <int> max-digits: 4;
    in property <bool> ok-visible: true;
    width: 288px;
    callback ok-clicked;
    in property <string> title;
    background: white;
    in-out property <int> number;
    in-out property <string> display-postfix: " g";
    in-out property <string> display-error;
    function pressed-digit(digit: int) {
        if log(number, 10) < max-digits - 1 {
            number = number * 10 + digit;
            display-error = "";
        }
    }
    main := VerticalLayout {
        Display {
            height: root.height / 5;
            postfix: display-postfix;
            number: root.number;
            display-error: display-error;
        }

        HorizontalLayout {
            vertical-stretch: 1;
            NumButton {
                digit: 7;
                key-pressed(digit) => {
                    pressed-digit(digit);
                }
            }

            NumButton {
                digit: 8;
                key-pressed(digit) => {
                    pressed-digit(digit);
                }
            }

            NumButton {
                digit: 9;
                key-pressed(digit) => {
                    pressed-digit(digit);
                }
            }
        }

        HorizontalLayout {
            NumButton {
                digit: 4;
                key-pressed(digit) => {
                    pressed-digit(digit);
                }
            }

            NumButton {
                digit: 5;
                key-pressed(digit) => {
                    pressed-digit(digit);
                }
            }

            NumButton {
                digit: 6;
                key-pressed(digit) => {
                    pressed-digit(digit);
                }
            }
        }

        HorizontalLayout {
            NumButton {
                digit: 1;
                key-pressed(digit) => {
                    pressed-digit(digit);
                }
            }

            NumButton {
                digit: 2;
                key-pressed(digit) => {
                    pressed-digit(digit);
                }
            }

            NumButton {
                digit: 3;
                key-pressed(digit) => {
                    pressed-digit(digit);
                }
            }
        }

        HorizontalLayout {
            NumButton {
                text: "Del";
                key-pressed(digit) => {
                    root.number = floor(root.number / 10);
                    display-error = "";
                }
            }

            NumButton {
                digit: 0;
                key-pressed(digit) => {
                    pressed-digit(digit);
                }
            }

            NumButton {
                text: ok-visible ? "Ok" : "";
                key-pressed(digit) => {
                    if ok-visible {
                        root.ok-clicked();
                    }
                }
            }
        }
    }

    Rectangle {
        y: main.y - 1px;
        width: main.width;
        border-color: black;
        border-width: 1px;
    }
}
