import { MyButton, Title } from "framework/widgets.slint";
import { NumPad } from "numpad.slint";
import { AppBackend, AppState, SpoolScaleState } from "app.slint";
import { Translations } from "translations.slint";

export component ScaleCalibration inherits VerticalLayout {
        callback ok-clicked;
        callback cancel-clicked;

        my-title:= Title {
          height: 40px;
          property <string> calibration-status: AppState.spool-scale-state == SpoolScaleState.Uncalibrated ? (Translations.tr-calibration-status-uncalibrated + " (\{AppState.spool-scale-raw-data})") : Translations.tr-calibration-status-calibrated;
          text: Translations.tr-scale-calibration-prefix + calibration-status;
        }
        HorizontalLayout {
            Rectangle {
                background: white;
                min-width: 0px;
                horizontal-stretch: 1;
                VerticalLayout {
                  padding-left: 5px;
                  padding-right: 5px;
                  Rectangle {
                    Text {
                      max-height: (root.height - my-title.height) / 5;
                      width: parent.width;
                      font-size: 20px;
                        horizontal-alignment: left;
                        text: Translations.tr-calib-step1;
                        wrap: word-wrap;
                    }
                  }
                  MyButton {
                      height: (root.height - my-title.height) / 5;
                      text: Translations.tr-press-tare;
                      clicked => {
                         AppBackend.calibrate-scale(0);
                      }
                  }
                  Rectangle {
                    Text {
                      max-height: (root.height - my-title.height) / 5 * 2;
                      width: parent.width;
                      font-size: 20px;
                        horizontal-alignment: left;
                        text: Translations.tr-calib-step2;
                        wrap: word-wrap;
                    }
                  }
                  MyButton {
                      height: (root.height - my-title.height) / 5;
                      text: Translations.tr-or-cancel;
                      clicked => { root.cancel-clicked(); }
                  }
                }
            }

            numpad := NumPad {
                height: root.height - my-title.height;
                title: Translations.tr-calibration-weight;
                ok-clicked => { 
                  root.ok-clicked(); 
                  AppBackend.calibrate-scale(self.number);
                }
            }
        }
    }
