import { MyText } from "framework/widgets.slint";
import { LabeledText } from "app-widgets.slint";
import { UiTray, UiTrayState, AppState, AppBackend, UiSlotDisplay } from "app.slint";
import { Translations } from "translations.slint";

component LabeledInfo inherits LabeledText {
    label-width: 90px;
}

export component SlotDisplay inherits Rectangle {
    background: white;
    in property <int> slot-index;
    property <UiTray> tray: AppState.trays-state[slot-index];
    property <UiSlotDisplay> display: AppBackend.get-slot-display(tray.id);

    VerticalLayout {
        alignment: stretch;
        Rectangle {
            vertical-stretch: 1;
            MyText {
                text: display.filament-title;
            }
        }

        padding: 10px;
        padding-bottom: 5px;

        LabeledInfo {
            vertical-stretch: 1;
            property <UiTrayState> state: tray.spool-state;
            label: Translations.tr-label-state;
            text: AppState.ui-tray-spool-state-name(tray.spool-state);
        }

        LabeledInfo {
            vertical-stretch: 1;
            label: Translations.tr-label-in-slicer;
            text: display.slicer-name;
        }

        HorizontalLayout {
            vertical-stretch: 1;
            alignment: space-between;
            LabeledInfo {
                horizontal-stretch: 1;
                label: Translations.tr-label-color;
                text: display.color-code;
            }

            LabeledInfo {
                label: Translations.tr-label-temps;
                text: "\{display.temp-min}°C - \{display.temp-max}°C";
            }
        }

        LabeledInfo {
            vertical-stretch: 1;
            label: Translations.tr-label-pa;
            text: display.pa;
        }

        LabeledInfo {
            vertical-stretch: 1;
            label-width: 240px;
            label: Translations.tr-label-consumed;
            text: display.consumed-since-loaded != 0 ? "\{Math.round(display.consumed-since-loaded*10)/10}g" : "–";
        }

    }
}
