import { Title, MyText,MyButton } from "./framework/widgets.slint";
import { AppBackend, AppState, ControlState, UiTray } from "app.slint";
import { Utils } from "utils.slint";
import { FrameworkState } from "framework/framework.slint";
import { FilamentInfoMode } from "app.slint";
// import { SelectIfNewSpool } from "core-weight.slint";

export component LabeledText inherits Rectangle {
    callback clicked;
    in-out property <bool> label-button: false;
    in-out property <string> label;
    in-out property <string> text;
    in-out property <color> label-color: blue;
    in-out property <color> text-color: black;
    in-out property <length> label-width;
    HorizontalLayout {
        thelabel := MyText {
            width: label-width;
            text: label;
            color: label-button ? black : label-color;
        }

        MyText {
            text: text;
            color: text-color;
        }
    }

    if label-button: MyButton {
        z: -1;
        x: thelabel.x - 4px;
        y: thelabel.y - 4px;
        width: thelabel.width - 1px; // for spacing of 5px (4+1) out of the 10px between elements
        height: thelabel.height + 8px;
        clicked => {
            root.clicked();
        }
    }
}

export component LabeledInfo inherits LabeledText {
    label-width: 90px;
}

export component EncodeTitle inherits Title {
    horizontal-alignment: right;
    text: "To Edit, Scan NFC With Phone   ▶ ▶ ▶\u{00A0}";
    text2: "\{FrameworkState.web-config-url}";
}

export component ViewTitle inherits Title {
    horizontal-alignment: center;
    text: "Filament Information";
}

export component EncodeButtons inherits HorizontalLayout {
    callback encode-clicked;
    callback cancel-clicked;

    Window {
        horizontal-stretch: 1;
    }

    MyButton {
        enabled: AppState.curr-encode-request-display.filament-type != "" && AppState.curr-encode-request-display.color-code != "";
        horizontal-stretch: 1;
        height: 56px;
        text: "Encode";
        clicked => {
            encode-clicked()
        }
    }

    MyButton {
        horizontal-stretch: 1;
        height: 56px;
        text: "Cancel";
        clicked => {
            cancel-clicked()
        }
    }
}

export component ViewButtons inherits HorizontalLayout {
    MyButton {
        horizontal-stretch: 1;
        height: 56px;
        text: "Close";
        clicked => {
            AppState.end-show-filament-information();
        }
    }
}

enum FilamentInfoState {
  DisplayInfo,
  SelectIfNewSpool,
}

export component FilamentInfo inherits Rectangle {
    in-out property <FilamentInfoMode> mode;
    property <FilamentInfoState> state: FilamentInfoState.DisplayInfo;
    width: 480px;
    height: 320px;
    background: white;
    // property <color> filament-color: mode == FilamentInfoMode.View ? (AppState.curr-encode-request.tray-index == 999 ? AppState.spool-staging-info.color : AppState.trays-state[AppState.curr-encode-request.tray-index].filament.color) :
    property <color> filament-color: AppState.curr-encode-request-display.title-color;

    VerticalLayout {
        alignment: stretch;

        // if mode == FilamentInfoMode.Encode: HorizontalLayout {
        //     MyButton {
        //         width: 80px;
        //         text: AppState.curr-encode-request.id != "" ? AppState.curr-encode-request.id : "Use ID";
        //         clicked => {
        //             AppState.encoding-select-spool-id = true;
        //         }
        //     }
        //
        //     EncodeTitle {
        //         background: filament-color;
        //         text-color: Utils.contrasting_color(filament-color);
        //     }
        // }

        if mode == FilamentInfoMode.View || mode == FilamentInfoMode.Wizard : HorizontalLayout {
            Rectangle {
                width: 80px;
                background: filament-color;
                border-color: black;
                border-width: 1px;
                MyText {
                    color: Utils.contrasting_color(filament-color);
                    text: AppState.curr-encode-request.id != "" ? AppState.curr-encode-request.id : "-";
                }
            }

            ViewTitle {
                background: filament-color;
                text-color: Utils.contrasting_color(filament-color);
            }
        }

        VerticalLayout {
            alignment: stretch;

            Rectangle {
                border-width: 1px;
                border-color: black;
                VerticalLayout {
                    padding: 10px;
                    spacing: 10px;
                    padding-bottom: 5px;
                    property <string> brand: AppState.curr-encode-request.brand == "" ? "[No Brand] " : "\{AppState.curr-encode-request.brand} ";
                    property <string> filament-subtype: " \{AppState.curr-encode-request.filament-subtype}";
                    property <string> color-name: AppState.curr-encode-request.color-name == "" ? " [No Color]" : " \{AppState.curr-encode-request.color-name}";
                    MyText {
                        horizontal-alignment: center;
                        text: "\{brand}\{AppState.curr-encode-request-display.filament-type}\{filament-subtype}\{color-name}";
                    }

                    LabeledInfo {
                        label: "Note:";
                        text: AppState.curr-encode-request.note;
                    }
                }
            }

            Rectangle {
                border-width: 1px;
                border-color: black;
                VerticalLayout {
                    padding: 10px;
                    spacing: 10px;
                    LabeledInfo {
                        label: "In Slicer:";
                        text: AppState.curr-encode-request-display.slicer-name;
                    }

                    HorizontalLayout {
                        alignment: space-between;
                        LabeledInfo {
                            horizontal-stretch: 1;
                            label: "Color";
                            text: "\{AppState.curr-encode-request-display.color-code}";
                        }

                        LabeledInfo {
                            label: "Temps: ";
                            text: "\{AppState.curr-encode-request-display.temp-min}°C - \{AppState.curr-encode-request-display.temp-max}°C";
                        }
                    }

                    VerticalLayout {
                        LabeledInfo {
                            label: "PA(K):";
                            text: AppState.curr-encode-request-display.pa-line1;
                        }

                        LabeledInfo {
                            label: "";
                            text: AppState.curr-encode-request-display.pa-line2;
                        }
                    }

                    LabeledInfo {
                        // label-button: mode == FilamentInfoMode.Encode;
                        property <string> core: AppState.curr-encode-request.weight-core > 0 ? "\{AppState.curr-encode-request.weight-core}g" : "—";
                        property <string> new: AppState.curr-encode-request.weight-new > 0 ? "\{AppState.curr-encode-request.weight-new}g" : "—";
                        property <string> advertised: AppState.curr-encode-request.weight-advertised <= 0 ? "—" : ((AppState.curr-encode-request.weight-advertised > 500) && (Math.mod(AppState.curr-encode-request.weight-advertised,500)) == 0) ? "\{AppState.curr-encode-request.weight-advertised / 1000}kg" : "\{AppState.curr-encode-request.weight-advertised}g";
                        label: "Weights:";
                        text: "\{advertised} (Label) / \{core} (Core) / \{new} (New)";
                        // clicked => {
                        //     AppState.encoding-spool-core-visible = true;
                        // }
                    }
                }
            }
        }

        // if mode == FilamentInfoMode.Encode: EncodeButtons {
        //     encode-clicked => {
        //         if AppState.curr-encode-request.encoded-as-new == EncodedAsNew.Unknown {
        //             state = FilamentInfoState.SelectIfNewSpool;
        //         } else {
        //             AppState.control-state = ControlState.Encoding;
        //             AppState.encode-start();
        //         }
        //     }
        //     cancel-clicked => {
        //         AppState.encode-cancel();
        //     }
        // }
        if mode == FilamentInfoMode.View: ViewButtons { }
    }

    // if mode == FilamentInfoMode.Encode && root.state == FilamentInfoState.SelectIfNewSpool: SelectIfNewSpool {
    //     cancel-clicked => {
    //         root.state = FilamentInfoState.DisplayInfo;
    //     }
    //
    //     yes-clicked => {
    //         AppState.curr-encode-request.weight-new = AppState.spool-scale-weight;
    //         AppState.curr-encode-request.encoded-as-new = EncodedAsNew.Yes;
    //         root.state = FilamentInfoState.DisplayInfo;
    //     }
    //     no-clicked => {
    //         AppState.curr-encode-request.weight-new = 0;
    //         AppState.curr-encode-request.encoded-as-new = EncodedAsNew.No;
    //         root.state = FilamentInfoState.DisplayInfo;
    //     }
    // }
}
