import { MyButton, Title } from "framework/widgets.slint";
import { NumPad } from "numpad.slint";
import { AppBackend, AppState } from "app.slint";

export component SelectInventoryId inherits Rectangle {
    background: black;
    property <string> error: "";
    in-out property <string> title: "Select Untagged Inventory Spool ID to Use";
    VerticalLayout {
        if root.title != "": Title {
            text: title;
        }

        HorizontalLayout {
            Rectangle { }

            num-pad-win := Window {
                width: num-pad.width;
                num-pad := NumPad {
                    display-postfix: "";
                    ok-clicked => {
                        error = AppBackend.fill-encode-request-from-spool-id(num-pad.number);
                        if error == "" {
                                // AppBackend.calc-encode-request-display(FilamentInfoMode.Encode);
                                AppState.encoding-select-spool-id = false;
                        } else {
                            num-pad.display-error = error;
                        }
                    }
                }
            }

            VerticalLayout {
                Rectangle {
                    vertical-stretch: 4;
                }

                Rectangle {
                    vertical-stretch: 1;
                    b := MyButton {
                        clicked => {
                            AppState.encoding-select-spool-id = false;
                        }
                        text: "Cancel";
                        height: num-pad-win.height / 5;
                    }
                }
            }
        }
    }
}
