import { MyText, MyButton } from "framework/widgets.slint";
import { AppState, AppConsts, AppBackend, SpoolStagingState, ControlState, SpoolScaleState, UiSpoolInfo } from "app.slint";
import { Utils } from "utils.slint"; 
import { FrameworkState } from "framework/framework.slint";

export component SpoolStaging inherits Window {
    callback clicked-ota;

    main := VerticalLayout {
        spacing: AppConsts.trays-spacing;
        title := Rectangle {
            background: AppConsts.title-gradient;
            height: 30px;
            Text {
                color: white; // Utils.contrasting_color(parent.background); // entered manually white because this cause a panic in slint for some reason
                text: AppState.spool-staging-state == SpoolStagingState.Empty ? "Staging" : AppState.spool-staging-state == SpoolStagingState.Scanned ? "Scanned" : AppState.spool-staging-state == SpoolStagingState.Encoded ? "Encoded" : "Unloaded";
                font-size: 20px;
            }

            title-border := Rectangle {
                border-color: black;
                border-width: 1px;
            }
        }

        Window {
            filament-box := Rectangle {
                background: (AppState.spool-staging-state != SpoolStagingState.Empty) ? AppState.spool-staging-info.color : AppConsts.no-color;

                if AppState.spool-staging-state != SpoolStagingState.Empty: 
                VerticalLayout {
                    property <bool> show-weight: AppState.spool-staging-info.weight-core > 0;
                    alignment: space-around;
                    padding-top: 8px;
                    padding-bottom: 8px;

                  // inventory-id
                  if AppState.spool-staging-info.id != "": inventory-id := Text {
                        padding: 0px;
                        horizontal-alignment: center;
                        font-size: 20px;
                        text: AppState.spool-staging-info.id != "" ? "ID: \{AppState.spool-staging-info.id}" : "";
                        color: Utils.contrasting_color(filament-box.background);
                    }

                    material := Text {
                        padding: 0px;
                        horizontal-alignment: center;
                        font-size: 20px;
                        text: AppState.spool-staging-info.material;
                        color: Utils.contrasting_color(filament-box.background);
                    }

                  // K Value (show only if no ID, otherwiser no room)
                  k-value := Text {
                        padding: 0px;
                        horizontal-alignment: center;
                        font-size: 20px;
                        text: "K " + ((AppState.spool-staging-info.k != "") ? AppState.spool-staging-info.k : "N/A");
                        color: Utils.contrasting_color(filament-box.background);
                    }

                  // // Spool Core Weight
                  // if self.show-weight: core-weigth := Text {
                  //       padding: 0px;
                  //       horizontal-alignment: center;
                  //       font-size: 20px;
                  //       text: (parent.show-weight ? "\{AppState.spool-staging-info.weight-core}g" : "");
                  //       color: Utils.contrasting_color(filament-box.background);
                  //   }
                }
            }

            if (AppState.spool-staging-state == SpoolStagingState.Empty && FrameworkState.ota-info.newer): 
            Rectangle {
                width: parent.width;
                height: parent.height;

                MyText {
                    color: lightgreen;
                    horizontal-alignment: center;
                    vertical-alignment: center;

                    text: "New\nVersion\n\{FrameworkState.ota-info.version}";
                }
            }

            filament-box-border := Rectangle {
                width: parent.width;
                height: parent.height;
                border-color: black;
                border-width: 1px;
            }
        }
    }

    // if AppState.control-state == ControlState.EncodeSelectSource && AppState.spool-staging-state == SpoolStagingState.Empty: encode-empty := Rectangle {
    //     background: beige;
    //     border-color: black;
    //     border-width: 1px;
    //     VerticalLayout {
    //         alignment: center;
    //         padding-top: 8px;
    //         padding-bottom: 8px;
    //         spacing: 10px;
    //         MyText {
    //             horizontal-alignment: center;
    //             text: "Start";
    //         }
    //         MyText {
    //             horizontal-alignment: center;
    //             text: "Clean";
    //         }
    //     }
    // }

    if (AppState.highlight-tray == 999 && AppState.highlight-tray-flash) || (AppState.highlight-staging): highlight-border := Rectangle {
        width: parent.width;
        height: parent.height;
        border-width: 4px;
        border-color: Utils.contrasting_color(filament-box.background);
    }

    area := TouchArea {
        width: parent.width;
        height: parent.height;
        clicked => {
            if AppState.spool-staging-state != SpoolStagingState.Empty {
              AppState.staging-selected();
                // if AppState.control-state == ControlState.StagingSelected { // second press on staging (next else is the first press)
                //     AppState.show-filament-information(999);
                // } else {
                //     AppState.control-state = ControlState.StagingSelected;
                // }
            } else if FrameworkState.ota-info.newer {
                root.clicked-ota();
            }
        }
    }
}
