import { Title, MyText, MyButton } from "./framework/widgets.slint";
import { AppBackend, AppState, ControlState, UiTray, UiSpoolRecord, UiSpoolRecordDisplay } from "app.slint";
import { Utils } from "utils.slint";
import { FrameworkState, Log } from "framework/framework.slint";
import { LabeledText } from "app-widgets.slint";


component LabeledInfo inherits LabeledText {
    label-width: 90px;
}

export component ViewTitle inherits Title {
    horizontal-alignment: center;
    text: "Filament Information";
}

export component ViewButtons inherits HorizontalLayout {
    MyButton {
        horizontal-stretch: 1;
        height: 56px;
        text: "Close";
        clicked => {
            AppState.control-state = ControlState.Ready;
        }
    }
}

export component SpoolDisplay inherits Rectangle {
    in-out property <UiSpoolRecordDisplay> spool-display;
    background: white;
    property <color> filament-color: spool-display.color;
    in property <bool> show-title: true;

    VerticalLayout {
        alignment: stretch;
        if show-title: Title {
            vertical-stretch: 0;
            background: spool-display.color;
            text-color: Utils.contrasting_color(self.background);
            text: "Spool \{spool-display.spool-record.id} Information";
        }

        VerticalLayout {
            alignment: stretch;
            vertical-stretch: 1;
            padding: 10px;
            padding-bottom: 5px;
            property <string> brand: spool-display.spool-record.brand == "" ? "" : "\{spool-display.spool-record.brand} ";
            property <string> material-subtype: spool-display.spool-record.material-subtype == "" ? "" : "\{spool-display.spool-record.material_subtype}";
            property <string> color-name: spool-display.spool-record.color-name == "" ? "" : " \{spool-display.spool-record.color-name}";
            MyText {
                vertical-stretch: 1;
                horizontal-alignment: center;
                text: "\{brand}\{spool-display.spool-record.material-type}\{material-subtype}\{color-name}";
            }

            LabeledInfo {
                vertical-stretch: 1;
                label: "Note:";
                text: spool-display.spool-record.note;
            }

            LabeledInfo {
                vertical-stretch: 1;
                label: "In Slicer:";
                text: spool-display.slicer-filament-name;
            }

            HorizontalLayout {
                vertical-stretch: 1;
                alignment: space-between;
                LabeledInfo {
                    horizontal-stretch: 1;
                    label: "Color:";
                    text: "\{spool-display.spool-record.color-code}";
                }

                LabeledInfo {
                    label: "Temps: ";
                    text: "\{spool-display.temp-min}°C - \{spool-display.temp-max}°C";
                }
            }

            LabeledInfo {
                vertical-stretch: 1;
                label: "PA(K):";
                text: spool-display.pa-line1;
            }

            VerticalLayout {
                vertical-stretch: 1;
                LabeledInfo {
                    property <string> core: spool-display.spool-record.weight-core > 0 ? "\{spool-display.spool-record.weight-core}g" : "—";
                    property <string> new: spool-display.spool-record.weight-new > 0 ? "\{spool-display.spool-record.weight-new}g" : "—";
                    property <string> advertised: spool-display.spool-record.weight-advertised <= 0 ? "—" : ((spool-display.spool-record.weight-advertised > 500) && (Math.mod(spool-display.spool-record.weight-advertised,500)) == 0) ? "\{spool-display.spool-record.weight-advertised / 1000}kg" : "\{spool-display.spool-record.weight-advertised}g";
                    label: "Weights:";
                    text: "Label: \{advertised} / Empty: \{core} / Full: \{new}";
                }

                LabeledInfo {
                    pure function calc-net(weight_new: int, weight_current: int, weight_core: int, weight_advertised: int) -> int {
                        // code from inventory adjusted to here
                        return weight_current != 0 && weight_core != 0
                          ? weight_current - weight_core
                          : (weight_current != 0 && weight_advertised != 0 && weight_new != 0
                            ? weight_current - (weight_new - weight_advertised)
                            : 0);
                      }
                    property <string> gross: spool-display.spool-record.weight-current > 0 ? "\{spool-display.spool-record.weight-current} g" : "—";
                    property <int> net_value: calc-net(spool-display.spool-record.weight-new, spool-display.spool-record.weight-current, spool-display.spool-record.weight-core, spool-display.spool-record.weight-advertised);
                    property <string> net: net_value != 0 ? "\{net_value} g" : "—";
                    label: "";
                    text: "Net: \{net} / Gross: \{gross}";
                }
            }
        }
    }
}
